### ISSUE TITLE
Error en la linea 68

### ISSUE THREAD

**Issue by RenzoCanales** [pedrosc16/Trivia_PedroZuniga#3]
### En la Linea 68 encontré un bug.

Al repetir por segunda vez una alternativa que no corresponde al 1 o 2 puesta por el usuario, se produce un error y no permite seguir la Trivia correspondiente.

### Adjunto link de la linea a resaltar.

```
File "main.py", line 68, in <module>
   value_one = int(input("\nColoca 1 para 'SI' o coloca 2 para 'NO' : "))
ValueError: invalid literal for int() with base 10: 'pedro'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "main.py", line 70, in <module>
   value_one = int(
ValueError: invalid literal for int() with base 10: 'pedro'
```

**Comment by pedrosc16** [comment]
Excelente acotacion de verdad no me habia percatado de ese error , estuve craneando por buen tiempo y pude encontrar la solucion  actualmente esa parte del codigo que generar error se encuentra asi : 

```
try:
    value_one = int(input("\nColoca 1 para 'SI' o coloca 2 para 'NO' : "))
except ValueError:
     value_one = int(input("\nNo escribas otro caracter ...Coloca 1 para 'SI' o coloca 2 para 'NO' : "))
```

Es decir si colocas un string en el valor de input te va a dar la posibilidad de pedir nuevamente un valor entero en este caso 1 o 2 sin embargo si por 2da vez le colocas un string , te brinda justo ese error que indicas en el issue.

### Solucion

La solucion seria que ello ingrese en un bucle hasta que el usuario ingrese un valor numerico 1 o 2 para ello le vamos a colocar un while y que rompa con un break el bucle en try, una vez que coloque el numero 1 o 2 de la siguiente forma : 

```
while True:
        try:
            value_one=int(input("\nColoca 1 para 'SI' o coloca 2 para 'NO' : "))
            break
                
        except ValueError:
                
            print("\nNo escribas otro caracter hiciste que tuviera un error")

```

Sin embargo ello conlleva a otro problema que cuando coloco un numero diferente al 1 o 2 , el codigo sigue avanzando con lo cual le tendria que añadir la validacion para que los numeros sean solo 1 o 2  mediante esta forma : 

```
while value_one!=1 or value_one!=2:
        value_one=int(input("\nColoca 1 para 'SI' o coloca 2 para 'NO' : "))
```

Y de esta manera estaria solucionado el bug , muchas gracias por tomarte el tiempo de ver el error que pudo haber tenido mi trivia , te invito a validar mi codigo con las soluciones brindadas y que puedas verificar mas errores o mejoras en mi codigo
